e-mart/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import default_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', default_home, name='default_home_name'),
    path('accounts/', include('accounts.url')),
    path('verification/', include('verify_email.urls')),
    path('wallet/', include('wallet.url'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ordered_item, name="ordered_item"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('product/description/<str:id>', views.product_info, name="product_description_page"),
    path('update_item/', views.updateItem, name="update_item"),
    path('previous/order', views.prev_orders, name="prev_orders"),
    path('previous/items/<str:id>', views.prev_items, name="prev_items"),
    path('review/item/<str:id>',views.review_items,name="review_page"),
    path('upvote/<str:id>',views.upvote_review,name="upvote"),
    path('downvote/<str:id>',views.downvote_review,name="downvote"),
    path("about/us",views.about_us_view,name='aboutus')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]


class CustomUser(AbstractUser):
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(unique=True)
    Gender = models.CharField(max_length=6, choices=GENDER_CHOICES,default='Male')
    Birthday = models.DateField(null=True,blank=True,auto_created=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits "
                                         "allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    profile_pic = models.ImageField(default="default.png", null=True, blank=True)
    proof = models.ImageField(default="default_proof.JPG", blank=True, null=True)
    address1 = models.CharField(max_length=100, blank=True, null=True)
    address2 = models.CharField(max_length=100, blank=True, null=True)
    pin_code = models.CharField(max_length=12, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=12, blank=True, null=True)

accounts/views.py
from django.shortcuts import render, redirect

from .form import CustomUserCreationForm, settigs_form, update_profile_form, passwordchangingform
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required
from verify_email.email_handler import send_verification_email


# Create your views here.

def hello_world(request):
    return render(request, 'accounts/home.html')


@unauthenticated_user
def login_views(request):
    form = CustomUserCreationForm()
    if request.method == "POST":
        if request.POST.get('submit') == 'sign_in':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('default_home_name')
            else:
                messages.info(request, "username or password is incorrect")
        if request.POST.get('submit') == 'sign_up':

            form = CustomUserCreationForm(request.POST)

            if form.is_valid():
                inactive_user = send_verification_email(request, form)
                user_name = form.cleaned_data.get('username')
            # if form.is_valid():
            #     #inactive_user = send_verification_email(request, form)
            #     form.save()
            #     user_name = form.cleaned_data.get('username')
            #     user = form.save(commit=False)
            #     user.save()

                messages.success(request,
                                 'The account was successfully created for ' + user_name + ', We sent a mail to you')
                return redirect('login_page')
            else:
                messages.error(request, f'The account was unsuccessfully created {form.error_messages}')
    context = {'form': form}

    return render(request, 'accounts/loginPage.html', context)



#
# @unauthenticated_user
# def register_views(request):
#     form = CustomUserCreationForm()
#
#     if request.method == 'POST':
#         print(request.POST.get('submit'))
#         form = CustomUserCreationForm(request.POST)
#         if form.is_valid():
#             inactive_user = send_verification_email(request, form)
#             # form.save()
#             # user = form.save(commit=False)
#             # user.save()
#             user_name = form.cleaned_data.get('username')
#             print(user_name)
#             messages.success(request,'Account was successfully created for ' + user_name + ' Email sent to your mail')
#             return redirect('login_page')
#
#         # else:
#         #
#         #     # messages.error(request, f'Account was unsuccessfully created {form.error_messages}')
#         #     return redirect('register_page')
#     context = {'form': form}
#     return render(request, 'accounts/registerPage.html', context)


@login_required(login_url='login_page')
def logout_view(request):
    logout(request)
    messages.success(request, 'You are successfully logged out')
    return redirect('login_page')


@login_required(login_url='login_page')
def default_home(request):
    print('default_home')
    group = None

    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
        print(group)

        if group == 'customer':
            # return redirect('customer_home')
            return redirect('hello')

        elif group == 'manager':
            # return redirect('manager_home')
            return redirect('hello')
        elif group == 'chef':
            # return redirect('chef_home')
            return redirect('hello')

        else:
            message = "You are not authorized to view this page"
            messages.error(request, message)
            return redirect('logout_page')
        # return HttpResponse('You are not authorized to view this page')
    else:
        print("home page")
        return redirect('ordered_item')


@login_required(login_url='login_page')
def settings_view(request):
    userr = request.user
    form = settigs_form(instance=userr)
    if request.method == 'POST':
        form = settigs_form(request.POST, request.FILES, instance=userr)
        if form.is_valid():
            form.save()
            print(form.cleaned_data["Birthday"])
            print("Form saved successfully")
            mssg = "Form saved successfully"
            messages.success(request,mssg)
            return redirect('settings')
        else:
            print("Form not saved")
            mssg = "Form not saved"
            messages.error(request,mssg)
            return redirect('settings')
    context = {'form': form}
    return render(request, 'accounts/settings.html', context)


@login_required(login_url='login_page')
def update_profile_view(request):
    user_pic = request.user
    form = update_profile_form(instance=user_pic)
    if request.method == "POST":
        form = update_profile_form(request.POST, request.FILES, instance=user_pic)
        user_pic.profile_pic.delete(save=True)
        if form.is_valid():
            form.save()
            return redirect('settings')
        else:
            return redirect('update_profile_pic')
    context = {"form": form}
    return render(request, "accounts/update_profile_pic.html", context)


class update_password(PasswordChangeView):
    form_class = passwordchangingform
    # messages.add_message(self.request, messages.INFO, 'Hello world.')
    success_message = "Your Password was successfully Changed!"
    success_url = reverse_lazy('settings')

accounts/templates/accounts/home.html
{#{% extends 'accounts/main.html' %}#}
{% extends 'store/main.html' %}
{% block content %}
<h1>Hii this is Home Page! </h1>

{% endblock %}

accounts/templates/accounts/loginPage.html
<!--
Source Code:"https://www.florin-pop.com/blog/2019/03/double-slider-sign-in-up-form/"
Thanks to "FLORIN POP"
-->
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style>

        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');

        * {
            box-sizing: border-box;
        }

        body {
            background: #f6f5f7;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            font-family: 'Montserrat', sans-serif;
            height: 100vh;
            margin: -20px 0 50px;
        }

        h1 {
            font-weight: bold;
            margin: 0;
        }

        h2 {
            text-align: center;
        }

        p {
            font-size: 14px;
            font-weight: 100;
            line-height: 20px;
            letter-spacing: 0.5px;
            margin: 20px 0 30px;
        }

        span {
            font-size: 12px;
        }

        a {
            color: #333;
            font-size: 14px;
            text-decoration: none;
            margin: 15px 0;
        }

        button {
            border-radius: 20px;
            border: 1px solid #FF4B2B;
            background-color: #FF4B2B;
            color: #FFFFFF;
            font-size: 12px;
            font-weight: bold;
            padding: 12px 45px;
            letter-spacing: 1px;
            text-transform: uppercase;
            transition: transform 80ms ease-in;
        }

        button:active {
            transform: scale(0.95);
        }

        button:focus {
            outline: none;
        }

        button.ghost {
            background-color: transparent;
            border-color: #FFFFFF;
        }

        form {
            background-color: #FFFFFF;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            padding: 0 50px;
            height: 100%;
            text-align: center;
        }

        input {
            background-color: #eee;
            border: none;
            padding: 12px 15px;
            margin: 8px 0;
            width: 100%;
        }

        .container {
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25),
            0 10px 10px rgba(0, 0, 0, 0.22);
            position: relative;
            overflow: hidden;
            width: 768px;
            max-width: 100%;
            min-height: 480px;
        }

        .form-container {
            position: absolute;
            top: 0;
            height: 100%;
            transition: all 0.6s ease-in-out;
        }

        .sign-in-container {
            left: 0;
            width: 50%;
            z-index: 2;
        }

        .container.right-panel-active .sign-in-container {
            transform: translateX(100%);
        }

        .sign-up-container {
            left: 0;
            width: 50%;
            opacity: 0;
            z-index: 1;
        }

        .container.right-panel-active .sign-up-container {
            transform: translateX(100%);
            opacity: 1;
            z-index: 5;
            animation: show 0.6s;
        }

        @keyframes show {
            0%, 49.99% {
                opacity: 0;
                z-index: 1;
            }

            50%, 100% {
                opacity: 1;
                z-index: 5;
            }
        }

        .overlay-container {
            position: absolute;
            top: 0;
            left: 50%;
            width: 50%;
            height: 100%;
            overflow: hidden;
            transition: transform 0.6s ease-in-out;
            z-index: 100;
        }

        .container.right-panel-active .overlay-container {
            transform: translateX(-100%);
        }

        .overlay {
            background: #FF416C;
            background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
            background: linear-gradient(to right, #FF4B2B, #FF416C);
            background-repeat: no-repeat;
            background-size: cover;
            background-position: 0 0;
            color: #FFFFFF;
            position: relative;
            left: -100%;
            height: 100%;
            width: 200%;
            transform: translateX(0);
            transition: transform 0.6s ease-in-out;
        }

        .container.right-panel-active .overlay {
            transform: translateX(50%);
        }

        .overlay-panel {
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            padding: 0 40px;
            text-align: center;
            top: 0;
            height: 100%;
            width: 50%;
            transform: translateX(0);
            transition: transform 0.6s ease-in-out;
        }

        .overlay-left {
            transform: translateX(-20%);
        }

        .container.right-panel-active .overlay-left {
            transform: translateX(0);
        }

        .overlay-right {
            right: 0;
            transform: translateX(0);
        }

        .container.right-panel-active .overlay-right {
            transform: translateX(20%);
        }

        .social-container {
            margin: 20px 0;
        }

        .social-container a {
            border: 1px solid #DDDDDD;
            border-radius: 50%;
            display: inline-flex;
            justify-content: center;
            align-items: center;
            margin: 0 5px;
            height: 40px;
            width: 40px;
        }

        footer {
            background-color: #222;
            color: #fff;
            font-size: 14px;
            bottom: 0;
            position: fixed;
            left: 0;
            right: 0;
            text-align: center;
            z-index: 999;
        }

        footer p {
            margin: 10px 0;
        }

        footer i {
            color: red;
        }

        footer a {
            color: #3c97bf;
            text-decoration: none;
        }

        #messages {
            background-color: #FF416C;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>


</head>


<div class="container" id="container">
    <div class="form-container sign-up-container">
        <form method="POST" action="">
            {% csrf_token %}
            <h1>Create Account</h1>

            <span>or use your email for registration</span>

            <input type="text" name="username" placeholder="Username....." maxlength="150" autofocus required
                   id="id_username">
            <input type="email" name="email" placeholder="Email......" maxlength="254" required id="id_email">
            <input type="password" name="password1" placeholder="Password....." autocomplete="new-password" required
                   id="id_password1">
            <input type="password" name="password2" placeholder="Renter Password....." autocomplete="new-password"
                   required id="id_password2">
            {% for message in messages %}
                <p id="messages">{{ message | title }}</p>
            {% endfor %}
            <button type='submit' name='submit' value='sign_up'>Sign Up</button>
        </form>
    </div>
    <div class="form-container sign-in-container">
        <form method="POST" action="">
            {% csrf_token %}
            <h1>Sign in</h1>
            <input type="text" name="username" placeholder="Username...">
            <input type="password" name="password" placeholder="Password....."/>
            {% for message in messages %}
                <p id="messages">{{ message | title }}</p>
            {% endfor %}
            <a href="#">Forgot your password?</a>
            <button type='submit' name='submit' value='sign_in'>Sign In</button>
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1>Welcome Back!</h1>
                <p>To keep connected with us please login with your personal info</p>
                <button class="ghost" id="signIn">Sign In</button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>Hello, Friend!</h1>
                <p>Enter your personal details and start journey with us</p>
                <button class="ghost" id="sign_Up">Sign Up</button>
            </div>
        </div>
    </div>
</div>

<footer>
    <p>
        Created with <i>♥</i> by Team 404
        </p>
</footer>
<script type="text/javascript" src="{% static 'js/login.js' %}"></script>

</body>

</html>

accounts/templates/accounts/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Hotel Management System</title>
    <script src="{% static 'js/realtime.js' %}"></script>
    <link rel="stylesheet" type="text/css" href={% static 'css/main.css' %}>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
</head>
<body onload="realtimeclock()">
{% include 'accounts/navbar.html' %}
{% block content %}


{% endblock %}
<hr>
<div style="padding: 20px">
<footer>NCP project</footer>
</div>
</body>
</html>

accounts/templates/accounts/navbar.html
<style>
    .hello-msg {
        font-size: 20px;
        color: white;
        margin-right: 20px;
    }

    .logout-msg {
        font-size: 15px;
        color: gainsboro;
        margin-right: 10px;
    }

    .time-msg {
        font-size: 15px;
        color: white;
        margin-right: 10px;
    }
</style>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'ordered_item' %}">Home </a>
            <a class="nav-item nav-link active" href="{% url 'settings' %}">settings</a>
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
    </div>
    {#    <span class="logout-msg">{% now "jS - F - Y  H:i:s" %}</span>#}
    <span><div id="clock" class="time-msg"><p>Time is precious.</p></div></span>
    <span class="hello-msg">Hello, {{ request.user }}</span>

    {% if request.user.is_anonymous %}
        <span><a class="logout-msg" href="{% url 'login_page' %}"> login</a></span>
    {% else %}
        <span><a class="logout-msg" href="{% url 'logout_page' %}"> Logout</a></span>
    {% endif %}
</nav>

accounts/templates/accounts/registerPage.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }

    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>


                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>

                </form>
            </div>

            <br>
            <div>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-primary" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-primary" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
            </div>

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'Email..';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>
</body>
</html>

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>register</title>#}
{#</head>#}
{#<body>#}
{#<h3>register</h3>#}
{#<form action="" method="POST" >#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" name="create">#}
{##}
{#</form>#}
{##}
{#</body>#}
{#</html>#}

accounts/templates/accounts/settings.html
{% extends 'store/main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{#    <script>#}
{#        $(function () {#}
{#            $("#id_Birthday").datetimepicker({#}
{#                format: 'd/m/Y H:i',#}
{#            });#}
{#        });#}
{#    </script>#}
    <style>
        .profile-pic {
            max-width: 200px;
            max-height: 200px;
            margin: 0 auto;
            border-radius: 50%;
        }

        .proof-pic {
            max-width: 100px;
            max-height: 100px;
            margin: 0 auto;
            overflow: hidden;
        }
    </style>

    <div>
        <div class="row">
            <div class="col-md-3">
                <div class="card card-body">
                    <a class="btn btn-warning" href="{% url 'update_profile_pic' %}"> &#8592; update profile</a>
                    <hr>
                    <h3 style="text-align: center">Account Settings</h3>
                    <hr>
                    <img class="profile-pic" src="{{ request.user.profile_pic.url }}">
                </div>
            </div>
        </div>
    </div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-3">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.Gender|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.Birthday|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    {{ form.phone_number|as_crispy_field }}
                </div>

                <div class="col-3">
                    {{ form.address1|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.address2|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.pin_code|as_crispy_field }}
                </div>
            </div>
            <div class="row">

                <div class="col-2">
                    {{ form.city|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.country|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.proof|as_crispy_field }}
                    <img class="proof-pic" src="{{ request.user.proof.url }}">
                </div>
                <div class="col-3">
                    <a class="btn btn-warning" href="{% url 'update_password' %}">update password</a>
                </div>
            </div>
            {{ form.errors }}
            <br>
            <input class="btn btn-primary" type="submit" name="save">
        </form>
    </div>

{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "store/main.html" %}
{% load static %}
{% block title %} Change Password {% endblock %}
{% block content %}
    <div class="form-group" style="margin:15px 10px 10px 25px ; width:30%">
<form method="post">
{% csrf_token %}
{{ form.as_p}}
<button class="btn btn-primary">change password</button>
</form>
        <br>
        <hr>
    <ul>
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    </div>
{% endblock %}

accounts/templates/accounts/update_profile_pic.html
{#{% extends "accounts/main.html" %}#}
{% extends 'store/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div style="padding: 20px">
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" name="save">
    </form>
    </div>
{% endblock %}